🗡️ RHOAI 3.0.0 - add resource flavor check 🗡️

diff --git a/applications/check-install/input/charts/check-install/check-install-configmap.yaml b/applications/check-install/input/charts/check-install/check-install-configmap.yaml
--- a/applications/check-install/input/charts/check-install/check-install-configmap.yaml
+++ b/applications/check-install/input/charts/check-install/check-install-configmap.yaml
@@ -111,7 +111,7 @@ data:
     check_istio_pods() {
         echo "🌴 Running check_istio_pods..."
         local i=0
-        PODS=$(oc get pods -n istio-system | wc -l)
+        PODS=$(oc get pods -n openshift-ingress -l app.kubernetes.io/instance=openshift-gateway-istiod --no-headers=true | wc -l)
         until [ "$PODS" > 0 ]
         do
             echo -e "${GREEN}Waiting for istio-system $PODS.${NC}"
@@ -121,16 +121,32 @@ data:
                 exit 1
             fi
             sleep 10
-            # RHOAI operator seems to get stuck sometimes here
-            # no kserve because istio has no pods
-            if [ "$PODS" -eq 0 ]  && [ "$i" > 100 ]; then
-                oc -n istio-system delete servicemeshcontrolplane data-science-smcp
-                oc delete pods --all -n redhat-ods-operator
-                sleep 120
-            fi
-            PODS=$(oc get pods -n istio-system | wc -l)
+            PODS=$(oc get pods -n openshift-ingress -l app.kubernetes.io/instance=openshift-gateway-istiod --no-headers=true | wc -l)
         done
         echo "🌴 check_istio_pods $PODS ran OK"
+    }
+
+    check_resource_flavor() {
+        echo "🌴 Running check_resource_flavor..."
+        local i=0
+        RF=$(oc get ResourceFlavor.kueue.x-k8s.io nvidia-gpu-flavor --no-headers=true | wc -l)
+        until [ "$RF" > 0 ]
+        do
+            echo -e "${GREEN}Waiting for nvidia-gpu-flavor $RF.${NC}"
+            ((i=i+1))
+            if [ $i -gt 200 ]; then
+                echo -e "🕱${RED}Failed - nvidia-gpu-flavor never ready - $RF?.${NC}"
+                exit 1
+            fi
+            sleep 10
+            # buggy 3.0 - ordering with cluster queue and gpu operator
+            if [ "$RF" -eq 0 ] && [ "$i" > 50 ]; then
+                oc delete ClusterQueue default 
+                sleep 15
+            fi
+            RF=$(oc get ResourceFlavor.kueue.x-k8s.io nvidia-gpu-flavor --no-headers=true | wc -l)
+        done
+        echo "🌴 check_resource_flavor $RF ran OK"
     }
 
     check_llm_pods() {
@@ -181,6 +197,7 @@ data:
     check_pods_allocatable
     check_gpus_allocatable
     check_istio_pods
+    check_resource_flavor
     check_llm_pods
     check_llama_stack
 
